
// Palavras Proibidas dentro dos nicks
const nicksProibidos = [
    'maduro',
    'discreto',
    'discretto',
    'discretoo',
    'dscreto',
    'madurao',
    'safado',
    'safada',
    'bancado',
    'xulo',
    'guloso',
    'casal',
    'casadobi',
    'bicasado',
    'sissy',
    'falodela',
    'falodelafone',
    'corno',
    'gay',
    'panuca',
    'prazer',
    'cazal',
    'madura',
    'ativo',
    'passivo',
    'xhxh',
    'csdo',
    'csda',
    'manso',
    'cormanso',
    '50tao',
    '60tao',
    '40tao',
    'caralhao',
    'policia',
    'maridoker',
    'maridoquer',
    'fetiches',
    'encontros',
    'encontro',
    'curioso',
    'curiosa',
    'cuck',
    'cuckold',
    'levei'
];

module.exports = nicksProibidos